(()=>{"use strict";const BASE="https://cdn.jsdelivr.net/gh/zaddy6969/KESAR@05aae2cd1d1ad4d662c48f02c15e5f33d1eae99b/script.js",$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,start=performance.now();document.body.classList.add("loader-hold");
const release=()=>setTimeout(()=>{document.body.classList.add("loaded","loader-release");document.body.classList.remove("loader-hold");setTimeout(()=>document.body.classList.add("loader-done"),1180)},Math.max(0,3200-(performance.now()-start)));
function story(){const a=$("#story .portrait img"),b=$("#story .small-portrait img"),c=$$("#story-craft .story-collage img");[[a,"/assets/images/storypage-mandi2.png"],[b,"/assets/images/storypage-spices2.png"],[c[0],"/assets/images/storypage-mandi2.png"],[c[1],"/assets/images/storypage-spices2.png"]].forEach(([img,src])=>{if(img){img.src=src;img.width=1122;img.height=1402}})}
function hero(){const media=$("#heroMedia"),img=media?.querySelector("img");if(!media||!img)return;img.classList.add("hero-fallback");img.src="/assets/images/heropage-mandi-4k.webp";media.querySelector(".hero-video")?.remove();const v=document.createElement("video");v.className="hero-video";v.autoplay=v.muted=v.loop=v.playsInline=true;v.preload="auto";v.poster=img.src;v.src="/assets/videos/heropage-mandi.mp4";v.setAttribute("aria-hidden","true");["canplay","loadeddata"].forEach(n=>v.addEventListener(n,()=>v.classList.add("is-ready"),{once:true}));v.addEventListener("error",()=>v.remove(),{once:true});img.after(v);if(!media.querySelector(".hero-glow")){const g=document.createElement("div");g.className="hero-glow";v.after(g)}v.play().catch(()=>{})}
const dishes=[
["Chicken Mandi","Mandi · Signature","Fragrant mandi rice served with tender, slow-roasted chicken.","Best enjoyed with house sauces and fresh salad.","/assets/images/menupage-chicken%20mandi.png"],
["Al Faham Chicken","Charcoal · Grill","Charcoal-grilled chicken marinated with aromatic Arabian-inspired spices.","Pair with mandi rice and cooling raita.","/assets/images/menupage-al%20faham.png"],
["Biryani","Rice · Classic","Aromatic long-grain basmati layered with spice and tender meat.","Complete the plate with raita and salad.","/assets/images/menupage-biryani.png"],
["Chicken Kebab","Grill · Sharing","Juicy chicken kebabs with warm spice and charred edges.","Serve with garlic dip and fresh salad.","/assets/images/menupage-chicken%20kebab.png"],
["Grill Chicken","Grill · House Favourite","Fire-grilled chicken finished with citrus and fragrant spice.","Best paired with mandi rice and house sauce.","/assets/images/menupage-grill%20chicken.png"],
["Kathi Rolls","Rolls · Street Classic","Soft flatbread wrapped around smoky chicken, vegetables and house sauce.","Perfect with a chilled drink.","/assets/images/menupage-kathi%20rolles.png"],
["Shawarma","Wrap · Classic","Tender spiced chicken, fresh vegetables and creamy sauce in a warm wrap.","Enjoy with fries and garlic sauce.","/assets/images/menupage-shawarma.png"],
["Tandoori Chicken","Tandoor · Classic","Deeply marinated chicken roasted in the tandoor until smoky and tender.","Best with mint chutney and onion salad.","/assets/images/menupage-tandoori%20chicken.png"]];
function modal(card,btn){const d=$("#dishDialog");if(!d)return;$("#dialogImage").src=$("img",card).src;$("#dialogImage").alt=$("img",card).alt;$("#dialogCategory").textContent=card.dataset.category;$("#dialogTitle").textContent=card.dataset.title;$("#dialogCopy").textContent=card.dataset.copy;$("#dialogPairing").textContent=card.dataset.pairing;document.body.classList.add("dialog-open");d.showModal();$(".dialog-close",d)?.focus();d.addEventListener("close",()=>btn.focus(),{once:true})}
function rail(){const t=$("#dishTrack");if(!t)return;t.innerHTML=dishes.map(d=>`<article class="dish-card reveal visible" data-title="${d[0]}" data-category="${d[1]}" data-copy="${d[2]}" data-pairing="${d[3]}"><img src="${d[4]}" alt="${d[0]}"><div><span>${d[1]}</span><h3>${d[0]}</h3><p>${d[2]}</p><button type="button" data-fixed-detail>View details ↗</button></div></article>`).join("");$$('[data-fixed-detail]',t).forEach(b=>b.onclick=()=>modal(b.closest(".dish-card"),b));const step=()=>{const c=$(".dish-card",t),g=parseFloat(getComputedStyle(t).gap||18);return c?c.getBoundingClientRect().width+g:t.clientWidth*.82},max=()=>t.scrollWidth-t.clientWidth,controls=()=>{const p=$("#dishPrev"),n=$("#dishNext");if(p)p.disabled=t.scrollLeft<=3;if(n)n.disabled=t.scrollLeft>=max()-3},bind=(id,dir)=>{const old=$(id);if(!old)return;const b=old.cloneNode(true);old.replaceWith(b);b.onclick=()=>t.scrollBy({left:dir*step(),behavior:reduced?"auto":"smooth"})};bind("#dishPrev",-1);bind("#dishNext",1);t.addEventListener("scroll",controls,{passive:true});t.addEventListener("wheel",e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();t.scrollLeft+=e.deltaY}},{passive:false});let drag=false,x=0,s=0;t.onpointerdown=e=>{if(e.target.closest("button,a"))return;drag=true;x=e.clientX;s=t.scrollLeft;t.classList.add("is-dragging");t.setPointerCapture(e.pointerId)};t.onpointermove=e=>{if(drag)t.scrollLeft=s-(e.clientX-x)};["pointerup","pointercancel"].forEach(n=>t.addEventListener(n,()=>{drag=false;t.classList.remove("is-dragging");controls()}));addEventListener("resize",controls,{passive:true});requestAnimationFrame(controls)}
function apply(){story();hero();rail();document.body.classList.add("loaded")}story();hero();release();const s=document.createElement("script");s.src=BASE;s.async=false;s.onload=()=>setTimeout(apply,0);s.onerror=apply;document.head.append(s)})();